---
- name: docker on Ubuntu
  hosts: all
  become: true
  tasks:

  - name: Install packages for HTTPS
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      state: latest

  - name: Add Docker’s official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present

  - name: Add docker repo
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
      filename: docker

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: Added user to group
    ansible.builtin.user:
     name: ubuntu
     groups: docker
